[package]
name = "discord-bot"
version = "0.1.0"
description = "A Discord Bot Application"
authors = ["Sabjen"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "discord_bot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.3", features = [] }
tauri-plugin-opener = "2.2.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"

serenity = { default-features = false, features = [ "full" ], version = "0.12" }
tokio = { version = "1.43.0", features = ["full"] }

rusqlite = { version = "0.33.0", features = ["bundled"] }
songbird = { version="0.4.6" }
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.4" }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
log = "0.4.25"
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2.2.1"
